#!/usr/bin/env bash
# This script transfers a file to a server using Secure Copy (SCP)

if [[ $# -ne 4 ]]; then
    echo "$0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path=$1
ip_address=$2
user=$3
ssh_key=$4

scp -o StrictHostKeyChecking=off -i "$ssh_key" "$file_path" "$user@$ip_address:/home/$user/"
