#!/usr/bin/env bash
# This script installs the Nginx web server and configures the initial "Hello
# world" page.

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: You need to be root to run this script" 1>&2
  exit 1
fi

# Update the package list and install Nginx
apt-get update
apt-get install -y nginx

# Create the default "Hello world" page
echo "Hello World!" > /var/www/html/index.html

echo -e "\tserver_name _;
\tlocation /redirect_me {
\t\treturn 301 https://lzcorp-landing-page.vercel.app/;
\t}" > /tmp/new_config

sed -i '/server_name _;/{
    r /tmp/new_config
    d
}' /etc/nginx/sites-available/default

# Start the Nginx service
service nginx restart

if [[ ! $? ]]; then
  echo "ERROR: Failed to start Nginx" 1>&2
  exit 1
fi

