#!/usr/bin/env bash
# This loops displays numbers 1 to 20 using the `while` loop and displays
	# "4" and then "bad luck from China" on the 4th iteration
	# "9" and then "bad luck from Japan" on the 9th iteration
	# "17" and then "bad luck from Italy" on the 17th iterations

i=1

while ((i  <= 20)); do
	
	echo "$i"

	case "$i" in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac

	((i++))
done
