#!/usr/bin/env bash
# This script displays the content of the current directory in a list format.
# Only the part of the name after the first dash is displayed.

for f in *; do 
	echo "$f" | cut -f 2 -d '-'
done
