#!/usr/bin/env bash
# This script gives information about a `school` file

if [ -e "school" ]; then
	echo "school file exists"
else
	echo "school file does not exist"
	exit # file does not exist, don't go any further.
fi

# check if the file is empty or not
if [ ! -s "school" ]; then
	echo "school file is empty"
else
	echo "school file is not empty"
fi

# check if the file is a regular file
if [ -f "school" ]; then
	echo "school is a regular file"
fi
