#!/usr/bin/env bash
# This script configures the firewall on the server

apt update
apt install ufw -y

ufw default deny incoming
ufw default allow outgoing

ufw allow ssh
ufw allow http
ufw allow https

ufw --force enable
