#!/usr/bin/env bash
# This script configures and runs `nginx` as the nginx user
sed -i "/user/c\user nginx;" /etc/nginx/nginx.conf
sed -i "s/\<80\>/8080/g" /etc/nginx/sites-available/default
pkill -9 apache2 # apache2 is running by default on port 8080 on the server
service nginx start
